# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore github4women/github4women.csproj
    - name: Build
      run: dotnet build github4women/github4women.csproj --no-restore
    - name: Buildando a aplicação
      run: echo "Buildando a aplicação"

  final-message:

    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Finalização
        run: echo " Todas as etapas concluídas com sucesso!"